# Broadcasting

Broadcasting is a powerful NumPy feature that allows you to perform arithmetic operations on arrays of different shapes.

### 💡 The Core Rule

Normally, to add or subtract two matrices, they must be the exact same size. Broadcasting breaks this rule. If one of your dimensions is exactly 1, NumPy will automatically "stretch" or duplicate that dimension to match the larger matrix.

---

### Example 1: Matrix + Scalar (The Simplest Stretch)

If you add a single number to a matrix, NumPy stretches that single number across every single position.

In [2]:
import numpy as np

matrix = np.array([[1, 2],
                   [3, 3]])

# Every single element gets 10 added to it
print(matrix+10)

[[11 12]
 [13 13]]


---

### Example 2: Matrix + Row Vector (Stretching Vertically)

Let's say you want to add a different bonus amount to each column of a matrix.

In [3]:
matrix = np.array([[10, 20], 
                   [30, 40]])

column_bonuses = np.array([1, 2])
# NumPy stretches column_bonuses vertically to become [[1, 2], [1, 2]]
print(matrix + column_bonuses)

[[11 22]
 [31 42]]


---

### Example 3: Matrix + Column Vector (Stretching Horizontally)

In [5]:
import numpy as np

# A 2x2 matrix of original scores
scores = np.array([80, 
                   90])

# A column vector: shape (2, 1)
# Student 0 gets +5 points, Student 1 gets +10 points
row_bonuses = np.array([[5], 
                        [10]])

# NumPy stretches row_bonuses horizontally to match the 2x2 shape
# It becomes: [[5,  5],
#]
print(scores + row_bonuses)

[[ 85  95]
 [ 90 100]]
