# 1. What Is NumPy?

NumPy (Numerical Python) provides the ndarray: an N-dimensional, homogeneous, fixed-type array.

| Feature    | Python List                   | NumPy Array                              |
| ---------- | ----------------------------- | ---------------------------------------- |
| Data types | Mixed (`int`, `str`, `float`) | Homogeneous (all `int64`, all `float64`) |
| Memory     | Scattered pointers            | Contiguous block                         |
| Speed      | Slow (Python loops)           | Fast (C vectorization)                   |
| Dimensions | Nested lists                  | Native N-D                               |
| Math ops   | Manual loops                  | Element-wise automatic                   |

In [2]:
import numpy as np

# A Python list
py_list = [1, 2, 3, 4, 5, 6]

# A NumPy array
arr = np.array([1, 2, 3, 4, 5, 6])

print(type(arr))

<class 'numpy.ndarray'>


---

# 2. Creating Arrays (Every Method)

**2.1 From Python Lists**

In [2]:
import numpy as np

# 1D
a = np.array([1, 2, 3])

# 2D (list of lists -> matrix)
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# 3D
c = np.array([[[1, 2], [3, 4], [5, 6], [7, 8]]])

print(f"{a}\n{"-"*4}\n{b}\n{"-"*4}\n{c}\n\n")

print(f"shape of a: {a.shape}")
print(f"shape of b: {b.shape}")
print(f"shape of c: {c.shape}")

[1 2 3]
----
[[1 2 3]
 [4 5 6]
 [7 8 9]]
----
[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


shape of a: (3,)
shape of b: (3, 3)
shape of c: (1, 4, 2)


**2.2 Built-in Constructors**

In [ ]:
print(np.zeros((3, 4)))             # 3x4 matrix of 0.0

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
print(np.ones((3, 4)))              # 2x3 matrix of 1.0

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [3]:
print(np.full((3,4), fill_value=7))            # 3x3 matrix filled with 7

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [9]:
print(np.eye(4))                    # 4x4 identity matrix (k argument modify diagonal position)

print("\n", "-"*14, "\n")

# using k argument to adjust diagonal position
print(np.eye(4, k=1))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

 -------------- 

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


In [ ]:
print(np.identity(3))               # 3x3 identity matrix (no K argument pure identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
print(np.empty((2, 2)))             # Uninitialized (fast, garbage values)

[[1. 1.]
 [1. 1.]]
