# Boolean Masking

Boolean masking allows you to filter elements in a matrix based on a condition (like "find all numbers greater than 10") without using slow for loops.

In [1]:
import numpy as np

matrix = np.array([
                 [1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12],
                 [13, 14, 15, 16]
                ])

In [2]:
# Step 1: Create the mask (the condition)
mask = matrix > 10

print("--- The Mask ---")
print(mask)

--- The Mask ---
[[False False False False]
 [False False False False]
 [False False  True  True]
 [ True  True  True  True]]


**Extracting the Data**: To extract the actual numbers, you pass that `mask` directly back into the matrix using brackets: `matrix[mask]`. NumPy will grab only the elements where the `mask` is True.

In [3]:
# Step 2: Apply the mask to extract the values
filtered_numbers = matrix[mask]

print("--- The Filtered Numbers ---")
print(filtered_numbers)

--- The Filtered Numbers ---
[11 12 13 14 15 16]


> Note: The output is flattened into a 1D array because the filtered results might not form a perfect rectangle anymore!

### PRO: Modify Data Instantly

In [4]:
# Copying matrix to keep the original safe
modified_matrix = matrix.copy()

# Set all values > 10 to 99
modified_matrix[modified_matrix > 10] = 99

print(modified_matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 99 99]
 [99 99 99 99]]
