# 1. Element-Wise Multiplication (* Operator)

If you use the standard asterisk (*), NumPy multiplies the matching positions of two matrices. The shapes of both matrices must match exactly.

In [2]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

result = A * B

print(result)

[[ 5 12]
 [21 32]]


Internal working:

```py
[[ 5 12]   # (1*5) and (2*6)
 [21 32]]  # (3*7) and (4*8)
```

---

# 2. True Matrix Multiplication (@ Operator or np.dot())

True matrix multiplication multiplies the rows of the first matrix by the columns of the second matrix. In modern Python, we use the `@` symbol for this, though you can also use `np.dot()`.

In [3]:
# True matrix multiplication
result_matrix = A @ B
# OR: result_matrix = np.dot(A, B)

print(result_matrix)

[[19 22]
 [43 50]]
