Previous page [04_numpy_multi_dim_indexing](04_numpy_multi_dim_indexing.ipynb).

---

# Array Slicing in NumPy

Its same as it works on normal Python list. If you know that then this is nothing.

**Syntax**: `[start:stop(exclusive):stride/step]`.

**1D syntax**: `[start:stop:step]`
**2D syntax**: `[start:stop:step][start:stop:step]` or using NumPy way `[start:stop:step, start:stop:step]` and so on for higher dimensions.

---

### Examples

In [3]:
import numpy as np

# 2d array: 4x4 matrix
matrix = np.array([
                 [1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12],
                 [13, 14, 15, 16]
                ])

print(matrix.shape)

(4, 4)


In [4]:
# Slicing [start, stop, step]

# print first row
print(matrix[0])

[1 2 3 4]


In [5]:
# print second row
print(matrix[1])

[5 6 7 8]


In [7]:
# last row
print(matrix[-1])

[13 14 15 16]


---

**Slicing Row Selection Examples**

In [8]:
# print first two rows using slicing
print(matrix[0:2])

[[1 2 3 4]
 [5 6 7 8]]


In [9]:
# print full matrix
print(matrix[:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [12]:
# print full matrix in reverse order
print(matrix[::-1])

[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [14]:
# print odd number indexes
print(matrix[1:4:2])

[[ 5  6  7  8]
 [13 14 15 16]]


In [17]:
# print even numbered indexes
print(matrix[0:4:2])
# OR
print(matrix[::2])

[[ 1  2  3  4]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 9 10 11 12]]


**Slicing Column Selection Examples**

In [4]:
# recreate it
matrix = np.array([
                 [1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12],
                 [13, 14, 15, 16]
                ])

print(matrix.shape)

(4, 4)


In [5]:
# print first column
print(matrix[:, 0])             # select all rows using `:` or entire matrix then access column 0

[ 1  5  9 13]


In [22]:
# print last column
print(matrix[:, -1])

[ 4  8 12 16]


In [6]:
# print last column reversed
last_column = matrix[:, -1]
reversed_column = np.flip(last_column)          # reverse using np.flip()
print(reversed_column)


# Alternative
last_col = matrix[:, -1]
print(last_col[::-1])

# OR: using single slicing line 
print(matrix[::-1, -1])                       # first reverse whole matrix using `::-1` and then print last column `-1`

# (Note: slicing applies to each list separately)
# if 2d matrix then [start:stop:step][start:stop:step] 
# OR numpy way[start:stop:step, start:stop:step]

# if there are even higher dimensions then same rule will be applied.

[16 12  8  4]
[16 12  8  4]
[16 12  8  4]


In [ ]:
# recreate it
matrix = np.array([
                 [1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12],
                 [13, 14, 15, 16]
                ])


# print last row reversed
print(matrix[-1, ::-1])

[16 15 14 13]


In [10]:
print(matrix[:, 0])

[ 1  5  9 13]


In [11]:
print(matrix[0:2, 0:2])

[[1 2]
 [5 6]]


In [13]:
# print first two columns
# select all rows `:`, and range of columns `0:2`
print(matrix[:, 0:2])

[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]


In [ ]:
# print last two columns
print(matrix[:, -2:])

[[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]]
