In [1]:
import numpy as np

In [3]:
# Scalar arithmetic

array = np.array([1, 2, 3])

print(array + 1)
print(array - 1)
print(array / 2)
print(array * 3)
print(array // 2)
print(array ** 2)

[2 3 4]
[0 1 2]
[0.5 1.  1.5]
[3 6 9]
[0 1 1]
[1 4 9]


### Vectorized Math Functions

In [15]:
arr = np.array([1, 2, 3, 4])

print(np.sqrt(arr))

[1.         1.41421356 1.73205081 2.        ]


In [21]:
rng = np.random.default_rng()

arr = np.full(shape=10, fill_value=2.3)

# Generates 10 distinct random numbers and multiplies element-by-element
arr = rng.random(size=arr.size)

print(arr)

[0.01221194 0.86342713 0.12911779 0.20713184 0.68400418 0.36137638
 0.36458833 0.29094358 0.57426338 0.70361794]


In [22]:
print(np.round(arr))

[0. 1. 0. 0. 1. 0. 0. 0. 1. 1.]


In [23]:
# to round down
print(np.floor(arr))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [24]:
# to round up
print(np.ceil(arr))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
